spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Shoppr
  datasource:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 5
    password: password
    url: jdbc:h2:mem:shopprdb
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
ping:
  message: ShopprDev is Live!
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"